// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiCkjCQjqY_M2bo9rK1uIz8na1SijcED8',
    appId: '1:295476608827:web:ee66e02988b31f229a811e',
    messagingSenderId: '295476608827',
    projectId: 'chat-app-c0bba',
    authDomain: 'chat-app-c0bba.firebaseapp.com',
    storageBucket: 'chat-app-c0bba.appspot.com',
    measurementId: 'G-LWTSD3BJ3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJeaGuj6D85wnST_xLqdp9ah_e3TdjHyM',
    appId: '1:295476608827:android:31caa8229e58a9c19a811e',
    messagingSenderId: '295476608827',
    projectId: 'chat-app-c0bba',
    storageBucket: 'chat-app-c0bba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPNjPbPWA_Udf2kWhb1rMI7Pm2OBgMMlg',
    appId: '1:295476608827:ios:b924a2aff5f1f02b9a811e',
    messagingSenderId: '295476608827',
    projectId: 'chat-app-c0bba',
    storageBucket: 'chat-app-c0bba.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPNjPbPWA_Udf2kWhb1rMI7Pm2OBgMMlg',
    appId: '1:295476608827:ios:b924a2aff5f1f02b9a811e',
    messagingSenderId: '295476608827',
    projectId: 'chat-app-c0bba',
    storageBucket: 'chat-app-c0bba.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiCkjCQjqY_M2bo9rK1uIz8na1SijcED8',
    appId: '1:295476608827:web:94abc326b002581e9a811e',
    messagingSenderId: '295476608827',
    projectId: 'chat-app-c0bba',
    authDomain: 'chat-app-c0bba.firebaseapp.com',
    storageBucket: 'chat-app-c0bba.appspot.com',
    measurementId: 'G-F2FVD8N9TV',
  );
}
